In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
import seaborn as sns

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tt/8t254_fd43l2np52syz3hzg00000gn/T/ipykernel_67858/555797462.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 26, in <module>
    from pandas.compat import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/compat/__init__.py", line 29, in <module>
    from pandas.compat.pyarrow import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/compat/pyarrow.py", line 8, in <module>
    import pyarrow as pa
  File "/opt/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tt/8t254_fd43l2np52syz3hzg00000gn/T/ipykernel_67858/555797462.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 9, in <module>
    from pandas.core.dtypes.dtypes import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/dtypes/dtypes.py", line 24, in <module>
    from pandas._libs import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pyarrow/__init__.py", line 65, in <module>
    import pyarrow.lib as _lib

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tt/8t254_fd43l2np52syz3hzg00000gn/T/ipykernel_67858/555797462.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 53, in <module>
    from pandas.core import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/ops/__init__.py", line 8, in <module>
    from pandas.core.ops.array_ops import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/ops/array_ops.py", line 56, in <module>
    from pandas.core.computation import expressions
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/computation/expressions.py", line 21, in <module>
    from pandas.core.computation.check import NUMEXPR_INSTALLED
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/computation/check.py", line 5, in <module>
    ne = import_optional_dependency("numexpr", errors="warn")
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda3/lib/python3.11/site-packages/numexpr/__init__.py", line 24, in <module>
    from numexpr.interpreter import MAX_THREADS, use_vml, __BLOCK_SIZE1__

AttributeError: _ARRAY_API not found

A module that was compiled using NumPy 1.x cannot be run in
NumPy 2.2.6 as it may crash. To support both 1.x and 2.x
versions of NumPy, modules must be compiled with NumPy 2.0.
Some module may need to rebuild instead e.g. with 'pybind11>=2.12'.

If you are a user of the module, the easiest solution will be to
downgrade to 'numpy<2' or try to upgrade the affected module.
We expect that some modules will need time to support NumPy 2.

Traceback (most recent call last):  File "/opt/anaconda3/lib/python3.11/runpy.py", line 198, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/opt/anaconda3/lib/python3.11/runpy.py", line 88, in _run_code
    exec(code, run_globals)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel_launcher.py", line 18, in <module>
    app.launch_new_instance()
  File "/opt/anaconda3/lib/python3.11/site-packages/traitlets/config/application.py", line 992, in launch_instance
    app.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelapp.py", line 739, in start
    self.io_loop.start()
  File "/opt/anaconda3/lib/python3.11/site-packages/tornado/platform/asyncio.py", line 195, in start
    self.asyncio_loop.run_forever()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 607, in run_forever
    self._run_once()
  File "/opt/anaconda3/lib/python3.11/asyncio/base_events.py", line 1922, in _run_once
    handle._run()
  File "/opt/anaconda3/lib/python3.11/asyncio/events.py", line 80, in _run
    self._context.run(self._callback, *self._args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 545, in dispatch_queue
    await self.process_one()
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 534, in process_one
    await dispatch(*args)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 437, in dispatch_shell
    await result
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 362, in execute_request
    await super().execute_request(stream, ident, parent)
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/kernelbase.py", line 778, in execute_request
    reply_content = await reply_content
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/ipkernel.py", line 449, in do_execute
    res = shell.run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/ipykernel/zmqshell.py", line 549, in run_cell
    return super().run_cell(*args, **kwargs)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3051, in run_cell
    result = self._run_cell(
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3106, in _run_cell
    result = runner(coro)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/async_helpers.py", line 129, in _pseudo_sync_runner
    coro.send(None)
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3311, in run_cell_async
    has_raised = await self.run_ast_nodes(code_ast.body, cell_name,
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3493, in run_ast_nodes
    if await self.run_code(code, result, async_=asy):
  File "/opt/anaconda3/lib/python3.11/site-packages/IPython/core/interactiveshell.py", line 3553, in run_code
    exec(code_obj, self.user_global_ns, self.user_ns)
  File "/var/folders/tt/8t254_fd43l2np52syz3hzg00000gn/T/ipykernel_67858/555797462.py", line 1, in <module>
    import pandas as pd
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/__init__.py", line 49, in <module>
    from pandas.core.api import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/api.py", line 28, in <module>
    from pandas.core.arrays import Categorical
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/__init__.py", line 1, in <module>
    from pandas.core.arrays.arrow import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/__init__.py", line 5, in <module>
    from pandas.core.arrays.arrow.array import ArrowExtensionArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/arrow/array.py", line 67, in <module>
    from pandas.core.arrays.masked import BaseMaskedArray
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/arrays/masked.py", line 61, in <module>
    from pandas.core import (
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/core/nanops.py", line 52, in <module>
    bn = import_optional_dependency("bottleneck", errors="warn")
  File "/opt/anaconda3/lib/python3.11/site-packages/pandas/compat/_optional.py", line 135, in import_optional_dependency
    module = importlib.import_module(name)
  File "/opt/anaconda3/lib/python3.11/importlib/__init__.py", line 126, in import_module
    return _bootstrap._gcd_import(name[level:], package, level)
  File "/opt/anaconda3/lib/python3.11/site-packages/bottleneck/__init__.py", line 7, in <module>
    from .move import (move_argmax, move_argmin, move_max, move_mean, move_median,

AttributeError: _ARRAY_API not found

In [2]:
df = pd.read_excel("Respiratory virus detections 2023.xlsx")
df

,WEEK,Covid_Tested,Covid_Positive,Covid_Ratio,Flu_Tested,Flu_Positive,Flu_Ratio,RSV_Tested,RSV_Positive,RSV_Ratio,...,ADV_Ratio,HMPV_Tested,HMPV_Positive,HMPV_Ratio,EV/RV_Tested,EV/RV_Positive,EV/RV_Ratio,HCoV_Tested,HCoV_Positive,HCoV_Ratio
0,202250,80681,10983,0.136129,38839,13239,0.340869,32706,2795,0.085458,...,0.024388,9615,178,0.018513,8299,380,0.045789,9586,488,0.050908
1,202251,69601,10866,0.156118,33205,5431,0.163560,30198,3028,0.100272,...,0.017980,10826,289,0.026695,9765,424,0.043420,9210,437,0.047448
2,202301,75090,11318,0.150726,37731,3414,0.090483,31402,3179,0.101236,...,0.018821,11770,337,0.028632,10693,449,0.041990,9894,439,0.044370
3,202302,71421,9575,0.134064,34515,1514,0.043865,29079,2671,0.091853,...,0.018670,10804,273,0.025268,9914,455,0.045895,9117,370,0.040584
4,202303,65762,8059,0.122548,29576,856,0.028942,25034,2043,0.081609,...,0.019403,9787,245,0.025033,8897,589,0.066202,8370,282,0.033692
5,202304,59990,6791,0.113202,28217,519,0.018393,23862,1885,0.078996,...,0.022913,9211,232,0.025187,8381,677,0.080778,7711,203,0.026326
6,202305,56805,6525,0.114867,27778,487,0.017532,23442,1667,0.071112,...,0.024115,9247,266,0.028766,8404,742,0.088291,7811,250,0.032006
7,202306,54717,6570,0.120072,27514,461,0.016755,23809,1361,0.057163,...,0.020910,8952,321,0.035858,8138,804,0.098796,7509,198,0.026368
8,202307,54612,6443,0.117978,25813,347,0.013443,22453,1155,0.051441,...,0.022944,8719,375,0.043010,7831,766,0.097816,7278,231,0.031739
9,202308,52076,6126,0.117636,24971,402,0.016099,21939,993,0.045262,...,0.027621,8511,358,0.042063,7686,725,0.094327,7092,216,0.030457
10,202309,53205,5955,0.111926,25245,466,0.018459,22219,821,0.036950,...,0.027571,8892,413,0.046446,8079,782,0.096794,7417,255,0.034380
11,202310,50807,5801,0.114177,24583,474,0.019282,21554,591,0.027420,...,0.027162,8460,416,0.049173,7598,709,0.093314,7012,259,0.036937
12,202311,49955,5796,0.116024,24304,511,0.021025,21099,459,0.021755,...,0.023884,8353,421,0.050401,7525,651,0.086512,6963,259,0.037197
13,202312,48292,5462,0.113104,23518,572,0.024322,20930,405,0.019350,...,0.025419,8437,452,0.053574,7758,717,0.092421,6999,316,0.045149
14,202313,45138,4862,0.107714,20931,656,0.031341,18676,313,0.016759,...,0.025273,7942,380,0.047847,7393,617,0.083457,6490,269,0.041448
15,202314,37325,3889,0.104193,20835,510,0.024478,18785,240,0.012776,...,0.023910,7387,343,0.046433,6832,608,0.088993,5982,269,0.044968
16,202315,41796,4744,0.113504,22968,708,0.030825,19763,278,0.014067,...,0.030717,7916,319,0.040298,7056,641,0.090845,6512,230,0.035319
17,202316,40181,4376,0.108907,21077,599,0.028420,18274,253,0.013845,...,0.028340,7533,291,0.038630,6670,573,0.085907,6225,231,0.037108
18,202317,37889,3805,0.100425,19982,534,0.026724,17339,204,0.011765,...,0.026138,7137,246,0.034468,6293,621,0.098681,5917,259,0.043772
19,202318,35349,3462,0.097938,19542,549,0.028093,17058,147,0.008618,...,0.036266,6891,224,0.032506,6045,662,0.109512,5566,191,0.034315
20,202319,32053,3083,0.096184,17881,488,0.027292,15599,109,0.006988,...,0.030449,6211,160,0.025761,5389,591,0.109668,5051,179,0.035439
21,202320,29063,2709,0.093211,16441,478,0.029074,14279,90,0.006303,...,0.031653,6279,113,0.017996,5548,592,0.106705,5048,138,0.027338
22,202321,26751,2438,0.091137,16241,346,0.021304,14212,59,0.004151,...,0.032892,5736,80,0.013947,5000,520,0.104000,4615,97,0.021018
23,202322,26681,2257,0.084592,16128,322,0.019965,14293,75,0.005247,...,0.029387,6017,72,0.011966,5266,527,0.100076,4984,109,0.021870
24,202323,24412,1819,0.074513,14031,257,0.018317,12953,52,0.004015,...,0.031469,5425,69,0.012719,4701,575,0.122314,4417,67,0.015169
25,202324,22696,1515,0.066752,13416,219,0.016324,12402,41,0.003306,...,0.041691,5167,49,0.009483,4403,533,0.121054,4154,65,0.015648
26,202325,20797,1279,0.061499,12555,179,0.014257,11600,41,0.003534,...,0.037485,4969,42,0.008452,4225,579,0.137041,4063,64,0.015752
27,202326,20073,1163,0.057939,12657,139,0.010982,11811,46,0.003895,...,0.035797,4757,47,0.009880,4001,497,0.124219,3803,42,0.011044
28,202327,19084,1100,0.057640,12126,117,0.009649,11360,37,0.003257,...,0.046785,4684,37,0.007899,3921,542,0.138230,3858,29,0.007517
29,202328,18719,1157,0.061809,11946,157,0.013142,11203,43,0.003838,...,0.041168,4933,27,0.005473,4204,565,0.134396,3994,25,0.006259
30,202329,16798,1146,0.068222,11022,104,0.009436,10406,50,0.004805,...,0.033581,4853,37,0.007624,4138,534,0.129048,3981,20,0.005024
31,202330,17944,1354,0.075457,11416,94,0.008234,10757,51,0.004741,...,0.034881,4932,18,0.003650,4149,541,0.130393,4067,22,0.005409
32,202331,17163,1468,0.085533,10150,76,0.007488,9531,46,0.004826,...,0.031655,3854,8,0.002076,3144,464,0.147583,3822,23,0.006018
33,202332,19127,1812,0.094735,11567,118,0.010201,10746,60,0.005583,...,0.023074,4993,21,0.004206,4206,571,0.135758,3994,15,0.003756
34,202333,21838,2529,0.115807,12631,145,0.011480,11668,52,0.004457,...,0.020973,5399,19,0.003519,4548,580,0.127529,4384,34,0.007755
35,202334,23381,3133,0.133998,13226,117,0.008846,12310,63,0.005118,...,0.016548,5006,15,0.002996,4547,570,0.125357,4447,26,0.005847
36,202335,21886,3305,0.151010,13360,166,0.012425,12464,76,0.006098,...,0.016334,5652,20,0.003539,4883,612,0.125333,4573,13,0.002843
37,202336,28182,4472,0.158683,15028,132,0.008784,13994,96,0.006860,...,0.014920,6059,23,0.003796,5126,759,0.148069,4896,19,0.003881
38,202337,30976,5140,0.165935,17363,138,0.007948,16177,124,0.007665,...,0.014765,6927,25,0.003609,5836,1056,0.180946,5646,10,0.001771
39,202338,35767,6665,0.186345,19666,168,0.008543,18368,201,0.010943,...,0.009242,7944,31,0.003902,6750,1353,0.200444,6546,27,0.004125
40,202339,40336,7892,0.195656,20939,190,0.009074,19663,222,0.011290,...,0.011824,8355,42,0.005027,7171,1343,0.187282,6701,17,0.002537
41,202340,42117,8342,0.198067,22749,245,0.010770,21172,286,0.013508,...,0.013166,8077,26,0.003219,6837,1205,0.176247,6551,18,0.002748
42,202341,38153,6682,0.175137,21711,174,0.008014,20306,364,0.017926,...,0.013517,7632,33,0.004324,5088,942,0.185142,6142,16,0.002605
43,202342,39259,6975,0.177666,22389,307,0.013712,20844,518,0.024851,...,0.014750,8039,40,0.004976,6944,892,0.128456,6410,9,0.001404
44,202343,37246,6676,0.179241,22025,466,0.021158,20753,676,0.032574,...,0.015051,7843,41,0.005228,7356,920,0.125068,6914,23,0.003327
45,202344,37956,6712,0.176836,24183,1026,0.042426,22822,924,0.040487,...,0.017338,8002,48,0.005999,8014,848,0.105815,7353,29,0.003944
46,202345,38465,6986,0.181620,24911,2043,0.082012,23247,1220,0.052480,...,0.014742,8960,53,0.005915,7834,836,0.106714,7302,31,0.004245
47,202346,41355,7772,0.187934,27368,3636,0.132856,25451,1502,0.059015,...,0.020379,9652,76,0.007874,8403,725,0.086279,7997,48,0.006002
48,202347,42135,8137,0.193117,28421,4175,0.146898,26160,1815,0.069381,...,0.019085,10286,108,0.010500,8797,653,0.074230,8423,56,0.006648
49,202348,43385,7876,0.181537,31048,5844,0.188225,28621,2032,0.070997,...,0.021348,10950,103,0.009406,9308,631,0.067791,9109,68,0.007465
50,202349,46500,8112,0.174452,32760,8582,0.261966,29587,2223,0.075134,...,0.018873,10897,131,0.012022,9221,543,0.058887,8664,97,0.011196
51,202350,41700,7796,0.186954,30444,9106,0.299107,26712,1885,0.070568,...,0.021836,8953,116,0.012957,7361,374,0.050808,8829,127,0.014384
52,202351,45408,7109,0.156558,40536,14051,0.346630,36345,2647,0.072830,...,0.017040,12395,218,0.017588,10427,475,0.045555,9891,247,0.024972

In [3]:
df.columns

Index(['WEEK', 'Covid_Tested', 'Covid_Positive', 'Covid_Ratio', 'Flu_Tested',
       'Flu_Positive', 'Flu_Ratio', 'RSV_Tested', 'RSV_Positive', 'RSV_Ratio',
       'HPIV_Tested', 'HPIV_Positive', 'HPIV_Ratio', 'ADV_Tested',
       'ADV_Positive', 'ADV_Ratio', 'HMPV_Tested', 'HMPV_Positive',
       'HMPV_Ratio', 'EV/RV_Tested', 'EV/RV_Positive', 'EV/RV_Ratio',
       'HCoV_Tested', 'HCoV_Positive', 'HCoV_Ratio'],
      dtype='object')

In [4]:
df.dtypes

WEEK                int64
Covid_Tested        int64
Covid_Positive      int64
Covid_Ratio       float64
Flu_Tested          int64
Flu_Positive        int64
Flu_Ratio         float64
RSV_Tested          int64
RSV_Positive        int64
RSV_Ratio         float64
HPIV_Tested         int64
HPIV_Positive       int64
HPIV_Ratio        float64
ADV_Tested          int64
ADV_Positive        int64
ADV_Ratio         float64
HMPV_Tested         int64
HMPV_Positive       int64
HMPV_Ratio        float64
EV/RV_Tested        int64
EV/RV_Positive      int64
EV/RV_Ratio       float64
HCoV_Tested         int64
HCoV_Positive       int64
HCoV_Ratio        float64
dtype: object

In [6]:
virus_cols = [
    'Covid_Ratio', 'Flu_Ratio', 'RSV_Ratio',
    'HPIV_Ratio', 'ADV_Ratio', 'HMPV_Ratio',
    'EV/RV_Ratio', 'HCoV_Ratio'
]

df = df[['WEEK'] + virus_cols].copy()

# % Removal → float conversion
for c in virus_cols:
    df[c] = (
        df[c].astype(str).str.replace('%', '', regex=False).replace('', '0').astype(float)
        / 100.0
    )
    
df

,WEEK,Covid_Ratio,Flu_Ratio,RSV_Ratio,HPIV_Ratio,ADV_Ratio,HMPV_Ratio,EV/RV_Ratio,HCoV_Ratio
0,202250,0.001361,0.003409,0.000855,0.000286,0.000244,0.000185,0.000458,0.000509
1,202251,0.001561,0.001636,0.001003,0.000326,0.000180,0.000267,0.000434,0.000474
2,202301,0.001507,0.000905,0.001012,0.000360,0.000188,0.000286,0.000420,0.000444
3,202302,0.001341,0.000439,0.000919,0.000317,0.000187,0.000253,0.000459,0.000406
4,202303,0.001225,0.000289,0.000816,0.000285,0.000194,0.000250,0.000662,0.000337
5,202304,0.001132,0.000184,0.000790,0.000269,0.000229,0.000252,0.000808,0.000263
6,202305,0.001149,0.000175,0.000711,0.000264,0.000241,0.000288,0.000883,0.000320
7,202306,0.001201,0.000168,0.000572,0.000269,0.000209,0.000359,0.000988,0.000264
8,202307,0.001180,0.000134,0.000514,0.000264,0.000229,0.000430,0.000978,0.000317
9,202308,0.001176,0.000161,0.000453,0.000250,0.000276,0.000421,0.000943,0.000305
10,202309,0.001119,0.000185,0.000370,0.000304,0.000276,0.000464,0.000968,0.000344
11,202310,0.001142,0.000193,0.000274,0.000276,0.000272,0.000492,0.000933,0.000369
12,202311,0.001160,0.000210,0.000218,0.000347,0.000239,0.000504,0.000865,0.000372
13,202312,0.001131,0.000243,0.000194,0.000289,0.000254,0.000536,0.000924,0.000451
14,202313,0.001077,0.000313,0.000168,0.000321,0.000253,0.000478,0.000835,0.000414
15,202314,0.001042,0.000245,0.000128,0.000339,0.000239,0.000464,0.000890,0.000450
16,202315,0.001135,0.000308,0.000141,0.000382,0.000307,0.000403,0.000908,0.000353
17,202316,0.001089,0.000284,0.000138,0.000387,0.000283,0.000386,0.000859,0.000371
18,202317,0.001004,0.000267,0.000118,0.000395,0.000261,0.000345,0.000987,0.000438
19,202318,0.000979,0.000281,0.000086,0.000467,0.000363,0.000325,0.001095,0.000343
20,202319,0.000962,0.000273,0.000070,0.000396,0.000304,0.000258,0.001097,0.000354
21,202320,0.000932,0.000291,0.000063,0.000407,0.000317,0.000180,0.001067,0.000273
22,202321,0.000911,0.000213,0.000042,0.000436,0.000329,0.000139,0.001040,0.000210
23,202322,0.000846,0.000200,0.000052,0.000492,0.000294,0.000120,0.001001,0.000219
24,202323,0.000745,0.000183,0.000040,0.000434,0.000315,0.000127,0.001223,0.000152
25,202324,0.000668,0.000163,0.000033,0.000428,0.000417,0.000095,0.001211,0.000156
26,202325,0.000615,0.000143,0.000035,0.000425,0.000375,0.000085,0.001370,0.000158
27,202326,0.000579,0.000110,0.000039,0.000412,0.000358,0.000099,0.001242,0.000110
28,202327,0.000576,0.000096,0.000033,0.000494,0.000468,0.000079,0.001382,0.000075
29,202328,0.000618,0.000131,0.000038,0.000421,0.000412,0.000055,0.001344,0.000063
30,202329,0.000682,0.000094,0.000048,0.000416,0.000336,0.000076,0.001290,0.000050
31,202330,0.000755,0.000082,0.000047,0.000337,0.000349,0.000036,0.001304,0.000054
32,202331,0.000855,0.000075,0.000048,0.000357,0.000317,0.000021,0.001476,0.000060
33,202332,0.000947,0.000102,0.000056,0.000316,0.000231,0.000042,0.001358,0.000038
34,202333,0.001158,0.000115,0.000045,0.000281,0.000210,0.000035,0.001275,0.000078
35,202334,0.001340,0.000088,0.000051,0.000215,0.000165,0.000030,0.001254,0.000058
36,202335,0.001510,0.000124,0.000061,0.000203,0.000163,0.000035,0.001253,0.000028
37,202336,0.001587,0.000088,0.000069,0.000149,0.000149,0.000038,0.001481,0.000039
38,202337,0.001659,0.000079,0.000077,0.000164,0.000148,0.000036,0.001809,0.000018
39,202338,0.001863,0.000085,0.000109,0.000180,0.000092,0.000039,0.002004,0.000041
40,202339,0.001957,0.000091,0.000113,0.000134,0.000118,0.000050,0.001873,0.000025
41,202340,0.001981,0.000108,0.000135,0.000138,0.000132,0.000032,0.001762,0.000027
42,202341,0.001751,0.000080,0.000179,0.000127,0.000135,0.000043,0.001851,0.000026
43,202342,0.001777,0.000137,0.000249,0.000156,0.000147,0.000050,0.001285,0.000014
44,202343,0.001792,0.000212,0.000326,0.000125,0.000151,0.000052,0.001251,0.000033
45,202344,0.001768,0.000424,0.000405,0.000146,0.000173,0.000060,0.001058,0.000039
46,202345,0.001816,0.000820,0.000525,0.000161,0.000147,0.000059,0.001067,0.000042
47,202346,0.001879,0.001329,0.000590,0.000144,0.000204,0.000079,0.000863,0.000060
48,202347,0.001931,0.001469,0.000694,0.000156,0.000191,0.000105,0.000742,0.000066
49,202348,0.001815,0.001882,0.000710,0.000152,0.000213,0.000094,0.000678,0.000075
50,202349,0.001745,0.002620,0.000751,0.000141,0.000189,0.000120,0.000589,0.000112
51,202350,0.001870,0.002991,0.000706,0.000144,0.000218,0.000130,0.000508,0.000144
52,202351,0.001566,0.003466,0.000728,0.000131,0.000170,0.000176,0.000456,0.000250

In [7]:
df.describe()

,WEEK,Covid_Ratio,Flu_Ratio,RSV_Ratio,HPIV_Ratio,ADV_Ratio,HMPV_Ratio,EV/RV_Ratio,HCoV_Ratio
count,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000,53.000000
mean,202323.150943,0.001267,0.000536,0.000314,0.000287,0.000243,0.000190,0.001071,0.000202
std,20.578551,0.000420,0.000851,0.000311,0.000113,0.000084,0.000160,0.000381,0.000158
min,202250.000000,0.000576,0.000075,0.000033,0.000125,0.000092,0.000021,0.000420,0.000014
25%,202312.000000,0.000962,0.000115,0.000056,0.000161,0.000180,0.000052,0.000863,0.000054
50%,202325.000000,0.001160,0.000193,0.000141,0.000286,0.000231,0.000120,0.001040,0.000156
75%,202338.000000,0.001659,0.000308,0.000572,0.000387,0.000304,0.000288,0.001285,0.000344
max,202351.000000,0.001981,0.003466,0.001012,0.000494,0.000468,0.000536,0.002004,0.000509

In [8]:
# Build 3-category-flag: 0 (Normal), 1 (Watch), 2 (Severe) for core variables influencing demand, supply chain directly
core_cols = ['Covid_Ratio', 'Flu_Ratio', 'RSV_Ratio'] 
  
# Threshold Creation
thresholds = {}

for col in core_cols:
    q = df[col].quantile([0.50, 0.75])
    thresholds[col] = {
        'q50': q.loc[0.50],
        'q75': q.loc[0.75]
    }


# Risk Flagging
def risk_flag(value, q50, q75):
    if value <= q50:
        return 0          # Normal
    elif value <= q75:
        return 1          # Watch
    else:
        return 2          # Severe


# Flag Column Creation
for col in core_cols:
    df[f'{col}_FLAG'] = df[col].apply(
        lambda x: risk_flag(
            x,
            thresholds[col]['q50'],
            thresholds[col]['q75']
        )
    )
    
# Use 'mean' to provide a more stable signal, reducing spikes
df['REDUCED_SUPPLY_CAPACITY_CORE'] = df[['Covid_Ratio_FLAG', 'Flu_Ratio_FLAG', 'RSV_Ratio_FLAG']].mean(axis=1)

def core_level(x):
    if x <= 0.5:
        return 0
    elif x <= 1.5:
        return 1
    else:
        return 2

df['REDUCED_SUPPLY_CAPACITY_CORE'] = df['REDUCED_SUPPLY_CAPACITY_CORE'].apply(core_level)

In [9]:
# Consider additive pressure by using the rest auxiliary variables that amplify the risk
aux_cols = ['HPIV_Ratio', 'ADV_Ratio', 'HMPV_Ratio', 'EV/RV_Ratio', 'HCoV_Ratio']

# Threshold Creation
aux_thresholds = {}
for col in aux_cols:
    q = df[col].quantile([0.50, 0.75])
    aux_thresholds[col] = {
        'watch': q.loc[0.50],
        'severe': q.loc[0.75]
    }

# Risk Flagging
for col in aux_cols:
    df[f'{col}_FLAG'] = df[col].apply(
        lambda x: risk_flag(
            x,
            aux_thresholds[col]['watch'],
            aux_thresholds[col]['severe']
        )
    )

# Additive Pressure (Depending on the severe count)
df['AUX_SEVERE_COUNT'] = (
    df[[f'{c}_FLAG' for c in aux_cols]] == 2
).sum(axis=1)

def aux_pressure(n):
    if n <= 2:
        return 0
    elif n <= 4:
        return 1
    else:
        return 2

df['AUX_ADDITIVE_PRESSURE'] = df['AUX_SEVERE_COUNT'].apply(aux_pressure)

# Combine with the reduced capacity for core variables
df['REDUCED_SUPPLY_CAPACITY_FINAL'] = (df['REDUCED_SUPPLY_CAPACITY_CORE']+df['AUX_ADDITIVE_PRESSURE']).clip(upper=2)

In [11]:
# Add T+2 lag; disease outbreaks(t) -> reduced supply capacity (t+2)
df = df.sort_values('WEEK').reset_index(drop=True)
df['REDUCED_SUPPLY_CAPACITY_LAG2'] = (df['REDUCED_SUPPLY_CAPACITY_FINAL'].shift(2).fillna(0).astype(int))

df

,WEEK,Covid_Ratio,Flu_Ratio,RSV_Ratio,HPIV_Ratio,ADV_Ratio,HMPV_Ratio,EV/RV_Ratio,HCoV_Ratio,Covid_Ratio_FLAG,...,REDUCED_SUPPLY_CAPACITY_CORE,HPIV_Ratio_FLAG,ADV_Ratio_FLAG,HMPV_Ratio_FLAG,EV/RV_Ratio_FLAG,HCoV_Ratio_FLAG,AUX_SEVERE_COUNT,AUX_ADDITIVE_PRESSURE,REDUCED_SUPPLY_CAPACITY_FINAL,REDUCED_SUPPLY_CAPACITY_LAG2
0,202250,0.001361,0.003409,0.000855,0.000286,0.000244,0.000185,0.000458,0.000509,1,...,2,0,1,1,0,2,1,0,2,0
1,202251,0.001561,0.001636,0.001003,0.000326,0.000180,0.000267,0.000434,0.000474,1,...,2,1,0,1,0,2,1,0,2,0
2,202301,0.001507,0.000905,0.001012,0.000360,0.000188,0.000286,0.000420,0.000444,1,...,2,1,0,1,0,2,1,0,2,2
3,202302,0.001341,0.000439,0.000919,0.000317,0.000187,0.000253,0.000459,0.000406,1,...,2,1,0,1,0,2,1,0,2,2
4,202303,0.001225,0.000289,0.000816,0.000285,0.000194,0.000250,0.000662,0.000337,1,...,1,0,0,1,0,1,0,0,1,2
5,202304,0.001132,0.000184,0.000790,0.000269,0.000229,0.000252,0.000808,0.000263,0,...,1,0,0,1,0,1,0,0,1,2
6,202305,0.001149,0.000175,0.000711,0.000264,0.000241,0.000288,0.000883,0.000320,0,...,1,0,1,1,0,1,0,0,1,1
7,202306,0.001201,0.000168,0.000572,0.000269,0.000209,0.000359,0.000988,0.000264,1,...,1,0,0,2,0,1,1,0,1,1
8,202307,0.001180,0.000134,0.000514,0.000264,0.000229,0.000430,0.000978,0.000317,1,...,1,0,0,2,0,1,1,0,1,1
9,202308,0.001176,0.000161,0.000453,0.000250,0.000276,0.000421,0.000943,0.000305,1,...,1,0,1,2,0,1,1,0,1,1
10,202309,0.001119,0.000185,0.000370,0.000304,0.000276,0.000464,0.000968,0.000344,0,...,0,1,1,2,0,1,1,0,0,1
11,202310,0.001142,0.000193,0.000274,0.000276,0.000272,0.000492,0.000933,0.000369,0,...,0,0,1,2,0,2,2,0,0,1
12,202311,0.001160,0.000210,0.000218,0.000347,0.000239,0.000504,0.000865,0.000372,0,...,1,1,1,2,0,2,2,0,1,0
13,202312,0.001131,0.000243,0.000194,0.000289,0.000254,0.000536,0.000924,0.000451,0,...,1,1,1,2,0,2,2,0,1,0
14,202313,0.001077,0.000313,0.000168,0.000321,0.000253,0.000478,0.000835,0.000414,0,...,1,1,1,2,0,2,2,0,1,1
15,202314,0.001042,0.000245,0.000128,0.000339,0.000239,0.000464,0.000890,0.000450,0,...,0,1,1,2,0,2,2,0,0,1
16,202315,0.001135,0.000308,0.000141,0.000382,0.000307,0.000403,0.000908,0.000353,0,...,0,1,2,2,0,2,3,1,1,1
17,202316,0.001089,0.000284,0.000138,0.000387,0.000283,0.000386,0.000859,0.000371,0,...,0,1,1,2,0,2,2,0,0,0
18,202317,0.001004,0.000267,0.000118,0.000395,0.000261,0.000345,0.000987,0.000438,0,...,0,2,1,2,0,2,3,1,1,1
19,202318,0.000979,0.000281,0.000086,0.000467,0.000363,0.000325,0.001095,0.000343,0,...,0,2,2,2,1,1,3,1,1,0
20,202319,0.000962,0.000273,0.000070,0.000396,0.000304,0.000258,0.001097,0.000354,0,...,0,2,1,1,1,2,2,0,0,1
21,202320,0.000932,0.000291,0.000063,0.000407,0.000317,0.000180,0.001067,0.000273,0,...,0,2,2,1,1,1,2,0,0,1
22,202321,0.000911,0.000213,0.000042,0.000436,0.000329,0.000139,0.001040,0.000210,0,...,0,2,2,1,0,1,2,0,0,0
23,202322,0.000846,0.000200,0.000052,0.000492,0.000294,0.000120,0.001001,0.000219,0,...,0,2,1,0,0,1,1,0,0,0
24,202323,0.000745,0.000183,0.000040,0.000434,0.000315,0.000127,0.001223,0.000152,0,...,0,2,2,1,1,0,2,0,0,0
25,202324,0.000668,0.000163,0.000033,0.000428,0.000417,0.000095,0.001211,0.000156,0,...,0,2,2,0,1,0,2,0,0,0
26,202325,0.000615,0.000143,0.000035,0.000425,0.000375,0.000085,0.001370,0.000158,0,...,0,2,2,0,2,1,3,1,1,0
27,202326,0.000579,0.000110,0.000039,0.000412,0.000358,0.000099,0.001242,0.000110,0,...,0,2,2,0,1,0,2,0,0,0
28,202327,0.000576,0.000096,0.000033,0.000494,0.000468,0.000079,0.001382,0.000075,0,...,0,2,2,0,2,0,3,1,1,1
29,202328,0.000618,0.000131,0.000038,0.000421,0.000412,0.000055,0.001344,0.000063,0,...,0,2,2,0,2,0,3,1,1,0
30,202329,0.000682,0.000094,0.000048,0.000416,0.000336,0.000076,0.001290,0.000050,0,...,0,2,2,0,2,0,3,1,1,1
31,202330,0.000755,0.000082,0.000047,0.000337,0.000349,0.000036,0.001304,0.000054,0,...,0,1,2,0,2,0,2,0,0,1
32,202331,0.000855,0.000075,0.000048,0.000357,0.000317,0.000021,0.001476,0.000060,0,...,0,1,2,0,2,0,2,0,0,1
33,202332,0.000947,0.000102,0.000056,0.000316,0.000231,0.000042,0.001358,0.000038,0,...,0,1,0,0,2,0,1,0,0,0
34,202333,0.001158,0.000115,0.000045,0.000281,0.000210,0.000035,0.001275,0.000078,0,...,0,0,0,0,1,0,0,0,0,0
35,202334,0.001340,0.000088,0.000051,0.000215,0.000165,0.000030,0.001254,0.000058,1,...,0,0,0,0,1,0,0,0,0,0
36,202335,0.001510,0.000124,0.000061,0.000203,0.000163,0.000035,0.001253,0.000028,1,...,0,0,0,0,1,0,0,0,0,0
37,202336,0.001587,0.000088,0.000069,0.000149,0.000149,0.000038,0.001481,0.000039,1,...,0,0,0,0,2,0,1,0,0,0
38,202337,0.001659,0.000079,0.000077,0.000164,0.000148,0.000036,0.001809,0.000018,1,...,0,0,0,0,2,0,1,0,0,0
39,202338,0.001863,0.000085,0.000109,0.000180,0.000092,0.000039,0.002004,0.000041,2,...,1,0,0,0,2,0,1,0,1,0
40,202339,0.001957,0.000091,0.000113,0.000134,0.000118,0.000050,0.001873,0.000025,2,...,1,0,0,0,2,0,1,0,1,0
41,202340,0.001981,0.000108,0.000135,0.000138,0.000132,0.000032,0.001762,0.000027,2,...,1,0,0,0,2,0,1,0,1,1
42,202341,0.001751,0.000080,0.000179,0.000127,0.000135,0.000043,0.001851,0.000026,2,...,1,0,0,0,2,0,1,0,1,1
43,202342,0.001777,0.000137,0.000249,0.000156,0.000147,0.000050,0.001285,0.000014,2,...,1,0,0,0,1,0,0,0,1,1
44,202343,0.001792,0.000212,0.000326,0.000125,0.000151,0.000052,0.001251,0.000033,2,...,1,0,0,0,1,0,0,0,1,1
45,202344,0.001768,0.000424,0.000405,0.000146,0.000173,0.000060,0.001058,0.000039,2,...,2,0,0,0,1,0,0,0,2,1
46,202345,0.001816,0.000820,0.000525,0.000161,0.000147,0.000059,0.001067,0.000042,2,...,2,0,0,0,1,0,0,0,2,1
47,202346,0.001879,0.001329,0.000590,0.000144,0.000204,0.000079,0.000863,0.000060,2,...,2,0,0,0,0,0,0,0,2,2
48,202347,0.001931,0.001469,0.000694,0.000156,0.000191,0.000105,0.000742,0.000066,2,...,2,0,0,0,0,0,0,0,2,2
49,202348,0.001815,0.001882,0.000710,0.000152,0.000213,0.000094,0.000678,0.000075,2,...,2,0,0,0,0,0,0,0,2,2
50,202349,0.001745,0.002620,0.000751,0.000141,0.000189,0.000120,0.000589,0.000112,2,...,2,0,0,0,0,0,0,0,2,2
51,202350,0.001870,0.002991,0.000706,0.000144,0.000218,0.000130,0.000508,0.000144,2,...,2,0,0,1,0,0,0,0,2,2
52,202351,0.001566,0.003466,0.000728,0.000131,0.000170,0.000176,0.000456,0.000250,1,...,2,0,0,1,0,1,0,0,2,2

In [12]:
df['REDUCED_SUPPLY_CAPACITY_LAG2'].value_counts().sort_index()

REDUCED_SUPPLY_CAPACITY_LAG2
0    21
1    22
2    10
Name: count, dtype: int64